
CREATE TABLE CAMPO_NOME
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	NOME VARCHAR(MAX),
	CAMPO_TABLE VARCHAR(MAX)
)

CREATE TABLE TICKET
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	CUSTOM1 VARCHAR(MAX),
	CUSTOM2 VARCHAR(MAX),
	CUSTOM3 VARCHAR(MAX),
)


--INSERT INTO CAMPO_NOME (NOME,CAMPO_TABLE) VALUES('[Nome]','CUSTOM1')
--INSERT INTO CAMPO_NOME (NOME,CAMPO_TABLE) VALUES('[E-mail]','CUSTOM2')

--INSERT INTO TICKET (CUSTOM1,CUSTOM2)VALUES('Ricardo Oliveira 1','ricardo1@gvp.com.br')
--INSERT INTO TICKET (CUSTOM1,CUSTOM2)VALUES('Ricardo Oliveira 2','ricardo2@gvp.com.br')
--INSERT INTO TICKET (CUSTOM1,CUSTOM2)VALUES('Ricardo Oliveira 3','ricardo3@gvp.com.br')
--INSERT INTO TICKET (CUSTOM1,CUSTOM2)VALUES('Ricardo Oliveira 4','ricardo4@gvp.com.br')

--SELECT STUFF(CAMPO_TABLE + ' ' + NOME, 1, 1, ',')  FROM CAMPO_NOME
--SELECT * FROM TICKET

DECLARE @COLUMNS NVARCHAR(MAX)
SET @COLUMNS =
(SELECT 
      STUFF(CAMPO_TABLE + ' ' + NOME, 1, 0, ',') 
FROM CAMPO_NOME SS 
ORDER BY 1
FOR XML PATH(''))

DECLARE @SQL NVARCHAR(MAX)

SET @SQL = 
' WITH PRODUTO AS
 (SELECT *,
          ROW_NUMBER() OVER(
                            ORDER BY NOME ASC ) AS ROWNUMBER
	   FROM (
				SELECT ' + SUBSTRING(@COLUMNS, 2, LEN(@COLUMNS)) + ' FROM TICKET_TESTE
			)  AS TEMPO)

		SELECT TOP (2) 
			PRODUTO.*,
		   Total = (SELECT COUNT(1) FROM PRODUTO)
		FROM PRODUTO
		WHERE ROWNUMBER > 0
	ORDER BY NOME ASC
'

PRINT @SQL
EXECUTE SP_EXECUTESQL @SQL
 
	