WITH PRODUTO AS
  (SELECT *,
          ROW_NUMBER() OVER(
                            ORDER BY NOME ASC , ID DESC) AS ROWNUMBER
   FROM
     (SELECT ID = CP.PASTA_ID,
             CP.NOME
      FROM VIVO_EMAIL_PASTA AS CP (NOLOCK)
      WHERE CP.IDC = '2758' ) AS TEMPO WHERE NOME LIKE '%V%')
	SELECT TOP (10) PRODUTO.*,
		   Total =
	  (SELECT COUNT(1)
	   FROM PRODUTO)
	FROM PRODUTO
	WHERE ROWNUMBER > 0
	ORDER BY NOME ASC,
	ID DESC