/*
	DECLARE @DATAINICIO DATETIME = '2020-04-24 12:59:12'
	DECLARE @DATAFIM DATETIME = '2020-04-30 12:59:12'
	DECLARE @IDGRUPO VARCHAR(MAX) = '1,2,3,4,5,6,7,8,9,10,11,12,13,14'
	DECLARE @TIMEZONE VARCHAR(MAX) = '-03:00:00'
	EXEC GETALLDAYSBETWEENTWODATE @DATAINICIO,@DATAFIM,@IDGRUPO,@TIMEZONE
*/

ALTER PROCEDURE GETALLDAYSBETWEENTWODATE    
(    
	@FROMDATE DATETIME,        
	@TODATE DATETIME,
	@IDGRUPO VARCHAR(MAX),
	@TIMEZONE VARCHAR(MAX) 
)   
AS    
BEGIN    
    DECLARE @TABLE TABLE (IDGRUPO INT, DATACRIACAO DATE,ENTRANTES INT,RECEBIDOS INT,ABONDONADOS INT,TEMPO_MEDIO_ABONDONO INT,OFFILINE INT,TEMPO_MEDIO_ESPERA INT,TEMPO_MEDIO_ATENDIMENTO INT,ATENDIMENTO_ATE_30_SEG INT)
	DECLARE @TABLE1 TABLE (IDGRUPO INT, DATACRIACAO DATE,ENTRANTES INT,RECEBIDOS INT,ABONDONADOS INT,TEMPO_MEDIO_ABONDONO INT,OFFILINE INT,TEMPO_MEDIO_ESPERA INT,TEMPO_MEDIO_ATENDIMENTO INT,ATENDIMENTO_ATE_30_SEG INT)
	DECLARE @HOUR INT =  SUBSTRING(@TIMEZONE, 1, 3)

    DECLARE @TOTALCOUNT INT    
    SET @FROMDATE = DATEADD(DAY,-1,DATEADD(HOUR,@HOUR,@FROMDATE))    
    SELECT  @TOTALCOUNT= DATEDIFF(DD,@FROMDATE,(DATEADD(HOUR,@HOUR,@TODATE)))
    
    ;WITH D AS     
            (    
              SELECT TOP (@TOTALCOUNT) ALLDAYS = DATEADD(DAY, ROW_NUMBER()     
                OVER (ORDER BY OBJECT_ID), REPLACE(@FROMDATE,'-',''))    
              FROM SYS.ALL_OBJECTS    
            )
		
	INSERT INTO @TABLE
    SELECT 0,CAST(ALLDAYS AS DATE) DATACRIACAO,ENTRANTES = 0,RECEBIDOS = 0,ABONDONADOS = 0,TEMPO_MEDIO_ABONDONO = 0,OFFILINE = 0,TEMPO_MEDIO_ESPERA = 0,TEMPO_MEDIO_ATENDIMENTO = 0,ATENDIMENTO_ATE_30_SEG = 0 FROM D    
    
	DECLARE @ID_GRUPO INT
	DECLARE CURSOR_GRUPO CURSOR FOR
	SELECT INTVALUE FROM [DBO].[CSVTOINT](@IDGRUPO)

	OPEN CURSOR_GRUPO
	FETCH NEXT FROM CURSOR_GRUPO INTO @ID_GRUPO

	WHILE @@FETCH_STATUS = 0
		BEGIN
			INSERT INTO @TABLE1
			SELECT @ID_GRUPO,DATACRIACAO,ENTRANTES,RECEBIDOS,ABONDONADOS,TEMPO_MEDIO_ABONDONO,OFFILINE,TEMPO_MEDIO_ESPERA,TEMPO_MEDIO_ATENDIMENTO,ATENDIMENTO_ATE_30_SEG FROM @TABLE  
			FETCH NEXT FROM CURSOR_GRUPO INTO  @ID_GRUPO
		END
	CLOSE CURSOR_GRUPO

	DEALLOCATE CURSOR_GRUPO

    SELECT * FROM @TABLE1 ORDER BY IDGRUPO, DATACRIACAO DESC
END 