
/*
		DECLARE @DATAINICIO DATETIME = '2019-01-24 12:59:12'
		DECLARE @DATAFIM DATETIME = '2020-04-30 12:59:12'
		DECLARE @IDGRUPO VARCHAR(MAX) = '1,2,3,4,5,6,7,8,9,10,11,12,13,14'
		DECLARE @TIMEZONE VARCHAR(MAX) ='-03:00:00'
		EXEC GETALLDAYSBETWEENTWOMONTH @DATAINICIO,@DATAFIM,@IDGRUPO,@TIMEZONE
*/

ALTER PROCEDURE GETALLDAYSBETWEENTWOMONTH    
(    
	@FROMDATE DATETIME,        
	@TODATE DATETIME,
	@IDGRUPO VARCHAR(MAX),
	@TIMEZONE VARCHAR(MAX)
)    
AS    
BEGIN    
    
	DECLARE @TABLE TABLE (IDGRUPO INT,ANO INT,MES_NUMERO INT, MES VARCHAR(MAX),ENTRANTES INT,RECEBIDOS INT,ABONDONADOS INT,TEMPO_MEDIO_ABONDONO INT,OFFILINE INT,TEMPO_MEDIO_ESPERA INT,TEMPO_MEDIO_ATENDIMENTO INT,ATENDIMENTO_ATE_30_SEG INT)
	DECLARE @TABLE1 TABLE (IDGRUPO INT,ANO INT,MES_NUMERO INT, MES VARCHAR(MAX),ENTRANTES INT,RECEBIDOS INT,ABONDONADOS INT,TEMPO_MEDIO_ABONDONO INT,OFFILINE INT,TEMPO_MEDIO_ESPERA INT,TEMPO_MEDIO_ATENDIMENTO INT,ATENDIMENTO_ATE_30_SEG INT)
	DECLARE @HOUR INT =  SUBSTRING(@TIMEZONE, 1, 3)

    DECLARE @TOTALCOUNT INT    
    SET @FROMDATE = DATEADD(MONTH,-1,DATEADD(HOUR,@HOUR,@FROMDATE))    
    SELECT @TOTALCOUNT= DATEDIFF(M,@FROMDATE,DATEADD(HOUR,@HOUR,@TODATE))
    
    ;WITH D AS     
            (    
              SELECT TOP (@TOTALCOUNT) ALLDAYS = DATEADD(MONTH, ROW_NUMBER()     
                OVER (ORDER BY OBJECT_ID), REPLACE(@FROMDATE,'-',''))    
              FROM SYS.ALL_OBJECTS    
            )
	INSERT INTO @TABLE		
    SELECT 0,YEAR(ALLDAYS) ANO,MONTH(ALLDAYS) MES_NUMERO,FORMAT(ALLDAYS, 'MMMM', 'pt-br') MES,ENTRANTES = 0,RECEBIDOS = 0,ABONDONADOS = 0,TEMPO_MEDIO_ABONDONO = 0,OFFILINE = 0,TEMPO_MEDIO_ESPERA = 0,TEMPO_MEDIO_ATENDIMENTO = 0 ,ATENDIMENTO_ATE_30_SEG = 0 FROM D    
        
	DECLARE @ID_GRUPO INT
	DECLARE CURSOR_GRUPO CURSOR FOR
	SELECT INTVALUE FROM [DBO].[CSVTOINT](@IDGRUPO)

	OPEN CURSOR_GRUPO

	FETCH NEXT FROM CURSOR_GRUPO INTO @ID_GRUPO
	WHILE @@FETCH_STATUS = 0
		BEGIN
			INSERT INTO @TABLE1
			SELECT @ID_GRUPO,ANO,MES_NUMERO,MES,ENTRANTES,RECEBIDOS,ABONDONADOS,TEMPO_MEDIO_ABONDONO,OFFILINE,TEMPO_MEDIO_ESPERA,TEMPO_MEDIO_ATENDIMENTO,ATENDIMENTO_ATE_30_SEG FROM @TABLE
			FETCH NEXT FROM CURSOR_GRUPO INTO  @ID_GRUPO
		END
	CLOSE CURSOR_GRUPO
	DEALLOCATE CURSOR_GRUPO

    SELECT * FROM @TABLE1 ORDER BY IDGRUPO,ANO DESC, MES_NUMERO ASC
END 

