/*
		DECLARE @IDCONTA INT = 84
		DECLARE @DATAINICIO DATETIME = '2020-05-20 00:59:12'
		DECLARE @DATAFIM DATETIME = '2020-05-20 14:59:12'
		DECLARE @IDGRUPO VARCHAR(MAX) = '1,2,3,4,5,6,7,8,9,10,11,12,13,14'	
		DECLARE @TIMEZONE VARCHAR(MAX)
		SELECT @TIMEZONE = T.UTCOFFSET FROM CONTA (NOLOCK) JOIN TIMEZONES T (NOLOCK) ON T.TIMEZONEID = CONTA.IDTIMEZONE WHERE CONTA.Id = @IDCONTA

		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'10',10,@TIMEZONE
*/

ALTER  PROC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX 
(	
	 @IDCONTA  INT 
	,@DATAINICIO DATETIME
	,@DATAFIM DATETIME
	,@IDGRUPO VARCHAR(MAX)
	,@HORAMASK VARCHAR(MAX) 
	,@HORA INT 
	,@TIMEZONE VARCHAR(MAX)
)
AS 

	BEGIN		
				DECLARE @HOUR INT =  REPLACE(SUBSTRING(@TIMEZONE, 1, 3),':','')
			
				DECLARE @TEMP TABLE(
									ID INT,
									IDCONTATO INT,
									IDPROPRIETARIO INT,
									DATACRIACAO DATETIME,
									CANAL VARCHAR(MAX),
									INTENCAO VARCHAR(MAX),
									SATISFATORIO INT,
									INSATISFATORIO INT,
									PERGUNTA VARCHAR(MAX),
									DATAINICIO DATETIME,
									DATACONCLUSAO DATETIME,
									DATAALTERACAO DATETIME
							  )  
				DECLARE @TEMP1 TABLE(
									ID INT,
									IDCONTATO INT,
									IDPROPRIETARIO INT,
									DATACRIACAO DATETIME,
									CANAL VARCHAR(MAX),
									INTENCAO VARCHAR(MAX),
									SATISFATORIO INT,
									INSATISFATORIO INT,
									PERGUNTA VARCHAR(MAX),
									DATAINICIO DATETIME,
									DATACONCLUSAO DATETIME,
									DATAALTERACAO DATETIME
							  ) 
			DECLARE @TABLE  TABLE(HORAMASK VARCHAR(MAX),HORA VARCHAR(MAX),MINUTO INT,CANAL VARCHAR(MAX),INTENCAO VARCHAR(MAX),PERGUNTA VARCHAR(MAX), SATISFATORIO INT,INSATISFATORIO INT,Total INT)
			
			DECLARE @TABLE1 TABLE(HORAMASK VARCHAR(MAX),HORA VARCHAR(MAX),MINUTO INT,CANAL VARCHAR(MAX),INTENCAO VARCHAR(MAX),PERGUNTA VARCHAR(MAX), SATISFATORIO INT,INSATISFATORIO INT,Total INT)

			INSERT INTO @TEMP
			SELECT 
				C.Id,
				C.IDCONTATO,
				C.IdProprietario,
				C.DATACRIACAO,
				CANAL = (SELECT TOP 1 CH.RESPOSTA FROM PROPRIEDADERESPOSTA CH (NOLOCK) WHERE  CH.IDUSER = C.ID AND CH.IdPropriedade IN (SELECT TOP 1 Id FROM Propriedade 
																									WHERE IdConta = @IdConta 
																											AND Nome = 'Chat' 
																											AND IdPropriedadeGrupo IN (SELECT Id FROM PropriedadeGrupo WHERE IdConta = @IdConta AND IdTipoCadastro = 10))),
	
				INTENCAO = (SELECT TOP 1 I.RESPOSTA FROM PROPRIEDADERESPOSTA I (NOLOCK) WHERE  I.IDUSER = T.ID AND I.IDPROPRIEDADE = (SELECT ID FROM PROPRIEDADE P (NOLOCK)WHERE P.IDCONTA = @IDCONTA AND P.NOME = 'INTENTION')), 
				(CASE WHEN PR.RESPOSTA = 'TRUE' THEN 1 ELSE 0 END)  SATISFATORIO,
				(CASE WHEN PR.RESPOSTA <> 'TRUE' THEN 1 ELSE 0 END)  INSATISFATORIO,
			     PERGUNTA = (SELECT TOP 1 PERGUNTA.RESPOSTA FROM PROPRIEDADERESPOSTA PERGUNTA (NOLOCK) WHERE PERGUNTA.IDUSER = T.ID AND PERGUNTA.IDPROPRIEDADE = (SELECT P.ID FROM PROPRIEDADE P(NOLOCK) WHERE P.IDCONTA = @IDCONTA AND P.NOME = 'QUESTION')),
				c.DATAINICIO,
				C.DATACONCLUSAO,
				C.DATAALTERACAO
			FROM CHAT C(NOLOCK)
			 JOIN GRUPOCHATSETTINGS GS (NOLOCK)ON C.IDGRUPOCHAT = GS.IDGRUPOCHAT 
			 JOIN TICKET T (NOLOCK) ON T.IDMODULO = C.ID AND T.MODULO = 'CHAT'
			 JOIN PROPRIEDADERESPOSTA PR (NOLOCK) ON PR.IDUSER = T.ID AND PR.IDPROPRIEDADE = (SELECT P.ID FROM PROPRIEDADE P(NOLOCK) WHERE P.IDCONTA = @IDCONTA AND P.NOME = 'CONCLUIDO')
			WHERE 
				C.IDCONTA = @IDCONTA 
				AND C.DATACRIACAO BETWEEN @DATAINICIO  AND @DATAFIM 
				AND C.IDGRUPOCHAT IN(SELECT INTVALUE FROM [DBO].[CSVTOINT](@IDGRUPO)) 
				AND GS.USABOT = 1    
				AND DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) = @HORA  AND (DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) >= 0 AND DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) <= 29) 

			INSERT INTO @TEMP1
			SELECT 
				C.Id,
				C.IDCONTATO,
				C.IdProprietario,
				C.DATACRIACAO,
				CANAL = (SELECT TOP 1 CH.RESPOSTA FROM PROPRIEDADERESPOSTA CH (NOLOCK) WHERE  CH.IDUSER = C.ID AND CH.IdPropriedade IN (SELECT TOP 1 Id FROM Propriedade 
																									WHERE IdConta = @IdConta 
																											AND Nome = 'Chat' 
																											AND IdPropriedadeGrupo IN (SELECT Id FROM PropriedadeGrupo WHERE IdConta = @IdConta AND IdTipoCadastro = 10))),
	
				INTENCAO = (SELECT TOP 1 I.RESPOSTA FROM PROPRIEDADERESPOSTA I (NOLOCK) WHERE  I.IDUSER = T.ID AND I.IDPROPRIEDADE = (SELECT ID FROM PROPRIEDADE P (NOLOCK)WHERE P.IDCONTA = @IDCONTA AND P.NOME = 'INTENTION')), 
				(CASE WHEN PR.RESPOSTA = 'TRUE' THEN 1 ELSE 0 END)  SATISFATORIO,
				(CASE WHEN PR.RESPOSTA <> 'TRUE' THEN 1 ELSE 0 END)  INSATISFATORIO,
			    PERGUNTA = (SELECT TOP 1 PERGUNTA.RESPOSTA FROM PROPRIEDADERESPOSTA PERGUNTA (NOLOCK) WHERE PERGUNTA.IDUSER = T.ID AND PERGUNTA.IDPROPRIEDADE = (SELECT P.ID FROM PROPRIEDADE P(NOLOCK) WHERE P.IDCONTA = @IDCONTA AND P.NOME = 'QUESTION')),
				c.DATAINICIO,
				C.DATACONCLUSAO,
				C.DATAALTERACAO
			FROM CHAT C(NOLOCK)
			 JOIN GRUPOCHATSETTINGS GS (NOLOCK)ON C.IDGRUPOCHAT = GS.IDGRUPOCHAT 
			 JOIN TICKET T (NOLOCK) ON T.IDMODULO = C.ID AND T.MODULO = 'CHAT'
			 JOIN PROPRIEDADERESPOSTA PR (NOLOCK) ON PR.IDUSER = T.ID AND PR.IDPROPRIEDADE = (SELECT P.ID FROM PROPRIEDADE P(NOLOCK) WHERE P.IDCONTA = @IDCONTA AND P.NOME = 'CONCLUIDO')
			WHERE 
				C.IDCONTA = @IDCONTA 
				AND C.DATACRIACAO BETWEEN @DATAINICIO  AND @DATAFIM 
				AND C.IDGRUPOCHAT IN(SELECT INTVALUE FROM [DBO].[CSVTOINT](@IDGRUPO)) 
				AND GS.USABOT = 1    
				AND DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) = @HORA  AND (DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) >= 30 AND DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) <= 59) 

	
			INSERT INTO @TABLE
		SELECT
			@HORAMASK + ':00hs - ' + @HORAMASK + ':29hs' AS HORAMASK, 
			@HORA AS HORA, 
			29 AS MINUTO, 
			CANAL [Canal],
			INTENCAO [Intenção],
			PERGUNTA,
			SUM(SATISFATORIO) [Satisfatório],
			SUM(INSATISFATORIO) [Insatisfatório],
			SUM(SATISFATORIO) + SUM(INSATISFATORIO) Total
		FROM @TEMP
		GROUP BY CANAL,INTENCAO,PERGUNTA,SATISFATORIO,DATACRIACAO

			INSERT INTO @TABLE1
		SELECT
			@HORAMASK + ':30hs - ' + @HORAMASK + ':59hs' AS HORAMASK, 
			@HORA AS HORA, 
			59 AS MINUTO, 
			CANAL [Canal],
			INTENCAO [Intenção],
			PERGUNTA,
			SUM(SATISFATORIO) [Satisfatório],
			SUM(INSATISFATORIO) [Insatisfatório],
			SUM(SATISFATORIO) + SUM(INSATISFATORIO) Total
		FROM @TEMP1
		GROUP BY CANAL,INTENCAO,PERGUNTA,SATISFATORIO,DATACRIACAO


			IF((SELECT COUNT(1) FROM @TABLE) = 0)
				BEGIN
					INSERT INTO @TABLE VALUES(@HORAMASK + ':00hs - ' + @HORAMASK + ':29hs',@HORA,29,'','','', 0,0,0)
				END

			IF((SELECT COUNT(1) FROM @TABLE1) = 0)
				BEGIN
					INSERT INTO @TABLE1 VALUES(@HORAMASK + ':30hs - ' + @HORAMASK + ':59hs',@HORA,59,'','','', 0,0,0)
				END
		
			SELECT * FROM @TABLE
			UNION
			SELECT * FROM @TABLE1

	END
