/*
		DECLARE @IDCONTA INT = 84
		DECLARE @DATAINICIO DATETIME = '2020-01-01 12:59:12'
		DECLARE @DATAFIM DATETIME = '2020-04-30 12:59:12'
		DECLARE @IDGRUPO VARCHAR(MAX) = '1,2,3,4,5,6,7,8,9,10,11,12,13,14'	
		DECLARE @ATENDENTE VARCHAR(MAX) = '1,7,9,11,20,23,71,73,101,105,106,110,142,143,150,229,237,243,244'
		DECLARE @TIMEZONE VARCHAR(MAX)
		SELECT @TIMEZONE = T.UTCOFFSET FROM CONTA (NOLOCK) JOIN TIMEZONES T (NOLOCK) ON T.TIMEZONEID = CONTA.IDTIMEZONE WHERE CONTA.Id = @IDCONTA

		EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'11',11,@TIMEZONE
*/

ALTER PROC PROC_CHAT_GRUPO_HORARIO_AUX 
(	
	 @IDCONTA  INT 
	,@DATAINICIO DATETIME
	,@DATAFIM DATETIME
	,@IDGRUPO VARCHAR(MAX)
	,@ATENDENTE VARCHAR(MAX)
	,@HORAMASK VARCHAR(MAX) 
	,@HORA INT 
	,@TIMEZONE VARCHAR(MAX)
)
AS 

	BEGIN		
			SET @ATENDENTE =  '0,' + @ATENDENTE
			DECLARE @HOUR INT =  REPLACE(SUBSTRING(@TIMEZONE, 1, 3),':','')

			SELECT
				C.IDGRUPOCHAT,
				DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) DATACRIACAO,
				@HORAMASK + ':00hs - ' + @HORAMASK + ':29hs' AS HORAMASK, 00 AS HORA, 29 AS MINUTO,
				SUM(1) ENTRANTES,
				SUM((CASE WHEN ISNULL(C.IDPROPRIETARIO,0) <> 0 THEN 1 ELSE 0 END)) RECEBIDOS,
				SUM((CASE WHEN ISNULL(C.IDPROPRIETARIO,0) = 0 THEN 1 ELSE 0 END)) ABONDONADOS,	
				(SELECT 
					AVG( DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,CC.DATACRIACAO),ISNULL(DATEADD(HOUR,@HOUR,CC.DATACONCLUSAO),DATEADD(HOUR,@HOUR,CC.DATACRIACAO)))) TEMPO_MEDIO_ABONDONO 
					FROM CHAT CC(NOLOCK)
					WHERE 
					CC.IDCONTA = @IDCONTA 
					AND CC.DATACRIACAO BETWEEN @DATAINICIO AND @DATAFIM 
					AND CC.IDGRUPOCHAT = C.IDGRUPOCHAT 
					AND ISNULL(CC.IDPROPRIETARIO,0) = 0
				GROUP BY IDGRUPOCHAT) TEMPO_MEDIO_ABONDONO,
				SUM((CASE WHEN C.IDSTATUS = 6 THEN 1 ELSE 0 END)) OFFILINE,
				AVG(DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,C.DATACRIACAO),COALESCE(DATEADD(HOUR,@HOUR,C.DATAINICIO), DATEADD(HOUR,@HOUR,C.DATACONCLUSAO), DATEADD(HOUR,@HOUR,C.DATAALTERACAO)))) TEMPO_MEDIO_ESPERA,
				(SELECT 
					AVG(DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,CC.DATAINICIO),ISNULL(DATEADD(HOUR,@HOUR,CC.DATACONCLUSAO),DATEADD(HOUR,@HOUR,CC.DATAALTERACAO)))) TEMPO_MEDIO_ATENDIMENTO 
					FROM CHAT CC(NOLOCK)
					WHERE 
					CC.IDCONTA = @IDCONTA 
					AND CC.DATACRIACAO BETWEEN @DATAINICIO AND @DATAFIM 
					AND CC.IDGRUPOCHAT = C.IDGRUPOCHAT 
					AND ISNULL(CC.IDPROPRIETARIO,0) <> 0
				GROUP BY IDGRUPOCHAT) TEMPO_MEDIO_ATENDIMENTO,
				SUM((CASE WHEN ISNULL(C.IDPROPRIETARIO,0) <> 0 AND DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,C.DATACRIACAO),ISNULL(DATEADD(HOUR,@HOUR,C.DATAINICIO),DATEADD(HOUR,@HOUR,C.DATACRIACAO))) <= 30 THEN 1 ELSE 0 END)) ATENDIMENTO_ATE_30_SEG
			FROM CHAT C(NOLOCK)
			WHERE 
				C.IDCONTA = @IDCONTA 
				AND C.DATACRIACAO BETWEEN @DATAINICIO  AND @DATAFIM 
				AND C.IDGRUPOCHAT IN(SELECT INTVALUE FROM [DBO].[CSVTOINT](@IDGRUPO)) 
				AND ISNULL(C.IDPROPRIETARIO,0) IN(SELECT INTVALUE FROM [DBO].[CSVTOINT](@ATENDENTE))
				AND DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) = @HORA  AND (DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) >= 0 AND DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) <= 29) 
			GROUP BY C.IDGRUPOCHAT,DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO))
	
		UNION 
			SELECT
				C.IDGRUPOCHAT,
				DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) DATACRIACAO,
				@HORAMASK + ':30hs - ' + @HORAMASK + ':59hs' AS HORAMASK, 30 AS HORA, 59 AS MINUTO,
				SUM(1) ENTRANTES,
				SUM((CASE WHEN ISNULL(C.IDPROPRIETARIO,0) <> 0 THEN 1 ELSE 0 END)) RECEBIDOS,
				SUM((CASE WHEN ISNULL(C.IDPROPRIETARIO,0) = 0 THEN 1 ELSE 0 END)) ABONDONADOS,	
				(SELECT 
					AVG( DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,CC.DATACRIACAO),ISNULL(DATEADD(HOUR,@HOUR,CC.DATACONCLUSAO),DATEADD(HOUR,@HOUR,CC.DATACRIACAO)))) TEMPO_MEDIO_ABONDONO 
					FROM CHAT CC(NOLOCK)
					WHERE 
					CC.IDCONTA = @IDCONTA 
					AND CC.DATACRIACAO BETWEEN @DATAINICIO AND @DATAFIM 
					AND CC.IDGRUPOCHAT = C.IDGRUPOCHAT 
					AND ISNULL(CC.IDPROPRIETARIO,0) = 0
				GROUP BY IDGRUPOCHAT) TEMPO_MEDIO_ABONDONO,
				SUM((CASE WHEN C.IDSTATUS = 6 THEN 1 ELSE 0 END)) OFFILINE,
				AVG(DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,C.DATACRIACAO),COALESCE(DATEADD(HOUR,@HOUR,C.DATAINICIO), DATEADD(HOUR,@HOUR,C.DATACONCLUSAO), DATEADD(HOUR,@HOUR,C.DATAALTERACAO)))) TEMPO_MEDIO_ESPERA,
				(SELECT 
					AVG(DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,CC.DATAINICIO),ISNULL(DATEADD(HOUR,@HOUR,CC.DATACONCLUSAO),DATEADD(HOUR,@HOUR,CC.DATAALTERACAO)))) TEMPO_MEDIO_ATENDIMENTO 
					FROM CHAT CC(NOLOCK)
					WHERE 
					CC.IDCONTA = @IDCONTA 
					AND CC.DATACRIACAO BETWEEN @DATAINICIO AND @DATAFIM 
					AND CC.IDGRUPOCHAT = C.IDGRUPOCHAT 
					AND ISNULL(CC.IDPROPRIETARIO,0) <> 0
				GROUP BY IDGRUPOCHAT) TEMPO_MEDIO_ATENDIMENTO,
				SUM((CASE WHEN ISNULL(C.IDPROPRIETARIO,0) <> 0 AND DATEDIFF(SECOND,DATEADD(HOUR,@HOUR,C.DATACRIACAO),ISNULL(DATEADD(HOUR,@HOUR,C.DATAINICIO),DATEADD(HOUR,@HOUR,C.DATACRIACAO))) <= 30 THEN 1 ELSE 0 END)) ATENDIMENTO_ATE_30_SEG
			FROM CHAT C(NOLOCK)
			WHERE 
				C.IDCONTA = @IDCONTA 
				AND C.DATACRIACAO BETWEEN @DATAINICIO  AND @DATAFIM 
				AND C.IDGRUPOCHAT IN(SELECT INTVALUE FROM [DBO].[CSVTOINT](@IDGRUPO)) 
				AND ISNULL(C.IDPROPRIETARIO,0) IN(SELECT INTVALUE FROM [DBO].[CSVTOINT](@ATENDENTE))
				AND DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) = @HORA  AND (DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) >= 30 AND DATEPART(MI,DATEADD(HOUR,@HOUR,C.DATACRIACAO)) <= 59) 
			GROUP BY C.IDGRUPOCHAT,DATEPART(HH,DATEADD(HOUR,@HOUR,C.DATACRIACAO))
	END



	