
/*
		DECLARE @IDCONTA INT = 84
		DECLARE @DATAINICIO DATETIME = '2020-05-20 00:59:12'
		DECLARE @DATAFIM DATETIME = '2020-05-20 23:59:12'
		DECLARE @IDGRUPO VARCHAR(MAX) = '13,14'	
		
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO
			
*/


ALTER PROC PROC_CHAT_BOT_PERGUNTA_HORARIO 
(	
	 @IDCONTA  INT 
	,@DATAINICIO DATETIME
	,@DATAFIM DATETIME
	,@IDGRUPO VARCHAR(MAX)
)
AS 
	BEGIN
		DECLARE @TABLE  TABLE(HORAMASK VARCHAR(MAX),HORA VARCHAR(MAX),MINUTO INT,CANAL VARCHAR(MAX),INTENCAO VARCHAR(MAX),PERGUNTA VARCHAR(MAX), SATISFATORIO INT,INSATISFATORIO INT,Total INT)

		DECLARE @TIMEZONE VARCHAR(MAX)
		SELECT @TIMEZONE = T.UTCOFFSET FROM CONTA (NOLOCK) JOIN TIMEZONES T (NOLOCK) ON T.TIMEZONEID = CONTA.IDTIMEZONE WHERE CONTA.Id = @IDCONTA

		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'00',0,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'01',1,@TIMEZONE
		INSERT INTO @TABLE 																		   
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'02',2,@TIMEZONE
		INSERT INTO @TABLE 																		   
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'03',3,@TIMEZONE
		INSERT INTO @TABLE 																		   
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'04',4,@TIMEZONE
		INSERT INTO @TABLE 																		   
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'05',5,@TIMEZONE
		INSERT INTO @TABLE 																		   
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'06',6,@TIMEZONE
		INSERT INTO @TABLE 																		   
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'07',7,@TIMEZONE
		INSERT INTO @TABLE 																		   
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'08',8,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'09',9,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'10',10,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'11',11,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'12',12,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'13',13,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'14',14,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'15',15,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'16',16,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'17',17,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'18',18,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'19',19,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'20',20,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'21',21,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'22',22,@TIMEZONE
		INSERT INTO @TABLE 
		EXEC PROC_CHAT_BOT_PERGUNTA_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,'23',23,@TIMEZONE
		
		SELECT HORAMASK [Horário],CANAL [Canal],INTENCAO [Inteção],PERGUNTA Pergunta, Satisfatório,Insatisfatório,Total FROM @TABLE
		ORDER BY HORAMASK 

	END
	
	