
/*

		DECLARE @IDCONTA INT = 84
		DECLARE @DATAINICIO DATETIME = '2020-01-01 12:59:12'
		DECLARE @DATAFIM DATETIME = '2020-04-30 12:59:12'
		DECLARE @IDGRUPO VARCHAR(MAX) = '1,2,3,4,5,6,7,8,9,10,11,12,13,14'	
		DECLARE @ATENDENTE VARCHAR(MAX) = '1,7,9,11,20,23,71,73,101,105,106,110,142,143,150,229,237,243,244'

		EXEC PROC_CHAT_GRUPO_HORARIO @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE

*/


ALTER PROC PROC_CHAT_GRUPO_HORARIO 
(	
	 @IDCONTA  INT 
	,@DATAINICIO DATETIME
	,@DATAFIM DATETIME
	,@IDGRUPO VARCHAR(MAX)
	,@ATENDENTE VARCHAR(MAX)
)
AS 
	BEGIN

			DECLARE @TIMEZONE VARCHAR(MAX)
			SELECT @TIMEZONE = T.UTCOFFSET FROM CONTA (NOLOCK) JOIN TIMEZONES T (NOLOCK) ON T.TIMEZONEID = CONTA.IDTIMEZONE WHERE CONTA.Id = @IDCONTA

			DECLARE @TABLE TABLE(IDGRUPOCHAT INT,DATACRIACAO INT,HORAMASK VARCHAR(MAX),HORA INT,MINUTO INT,ENTRANTES INT,RECEBIDOS INT,ABONDONADOS INT,TEMPO_MEDIO_ABONDONO INT,OFFILINE INT,TEMPO_MEDIO_ESPERA INT,TEMPO_MEDIO_ATENDIMENTO INT,ATENDIMENTO_ATE_30_SEG INT)
			DECLARE @TABLE1 TABLE(IDGRUPOCHAT INT,DATACRIACAO INT,HORAMASK VARCHAR(MAX),HORA INT,MINUTO INT,ENTRANTES INT,RECEBIDOS INT,ABONDONADOS INT,TEMPO_MEDIO_ABONDONO INT,OFFILINE INT,TEMPO_MEDIO_ESPERA INT,TEMPO_MEDIO_ATENDIMENTO INT,ATENDIMENTO_ATE_30_SEG INT)

			INSERT INTO @TABLE1 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX_TABLE_TEMP @IDGRUPO

			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'00',0 ,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'01',1,@TIMEZONE
			INSERT INTO @TABLE 																		   
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'02',2,@TIMEZONE
			INSERT INTO @TABLE 																		   
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'03',3,@TIMEZONE
			INSERT INTO @TABLE 																		   
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'04',4,@TIMEZONE
			INSERT INTO @TABLE 																		   
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'05',5,@TIMEZONE
			INSERT INTO @TABLE 																		   
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'06',6,@TIMEZONE
			INSERT INTO @TABLE 																		   
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'07',7,@TIMEZONE
			INSERT INTO @TABLE 																		   
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'08',8,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'09',9,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'10',10,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'11',11,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'12',12,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'13',13,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'14',14,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'15',15,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'16',16,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'17',17,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'18',18,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'19',19,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'20',20,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'21',21,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'22',22,@TIMEZONE
			INSERT INTO @TABLE 
			EXEC PROC_CHAT_GRUPO_HORARIO_AUX @IDCONTA,@DATAINICIO,@DATAFIM,@IDGRUPO,@ATENDENTE,'23',23,@TIMEZONE
			
			UPDATE
			    A
			SET
				A.HORA = B.HORA,
				A.MINUTO = B.MINUTO,
				A.ATENDIMENTO_ATE_30_SEG = B.ATENDIMENTO_ATE_30_SEG,
				A.ENTRANTES = B.ENTRANTES,
				A.RECEBIDOS = B.RECEBIDOS,
				A.ABONDONADOS = B.ABONDONADOS,
				A.TEMPO_MEDIO_ABONDONO = B.TEMPO_MEDIO_ABONDONO,
				A.OFFILINE = B.OFFILINE,
				A.TEMPO_MEDIO_ESPERA = B.TEMPO_MEDIO_ESPERA,
				A.TEMPO_MEDIO_ATENDIMENTO = B.TEMPO_MEDIO_ATENDIMENTO,
				A.DATACRIACAO = B.DATACRIACAO
			FROM @TABLE1 AS A INNER JOIN @TABLE AS B ON A.HORAMASK = B.HORAMASK AND A.IDGRUPOCHAT = B.IDGRUPOCHAT
			
			SELECT 
				Grupo = (SELECT GG.NOME FROM GRUPOCHAT GG (NOLOCK) WHERE GG.ID = IDGRUPOCHAT),
				HORAMASK,			
				ENTRANTES [Quantidades de chats recebidos],
				RECEBIDOS [Quantidade de chat atendidos],
				ROUND(CAST(((CAST(RECEBIDOS AS DECIMAL)/CAST((CASE WHEN ENTRANTES = 0 THEN 1 ELSE ENTRANTES END)  AS DECIMAL)) * 100) AS DECIMAL),2)[%de chat recebidos x atendidos],
				ABONDONADOS [Chat perdidos],
				ROUND(CAST(((CAST(ABONDONADOS AS DECIMAL)/CAST((CASE WHEN ENTRANTES = 0 THEN 1 ELSE ENTRANTES END) AS DECIMAL)) * 100) AS decimal),2)[%Taxa de perdido],
				CONVERT(VARCHAR, DATEADD(SECOND, ISNULL(TEMPO_MEDIO_ABONDONO,0), 0), 108)[Tempo médio de perdido],
				OFFILINE [chat fora do horário de atendimento],
				CONVERT(VARCHAR, DATEADD(SECOND, ISNULL(TEMPO_MEDIO_ESPERA,0), 0), 108) [Tempo Médio de espera para ser atendido],
				CONVERT(VARCHAR, DATEADD(SECOND, ISNULL(TEMPO_MEDIO_ATENDIMENTO,0), 0), 108) [Tempo Médio de Atendimento],
				CAST((CAST(ATENDIMENTO_ATE_30_SEG AS DECIMAL)/CAST((CASE WHEN RECEBIDOS = 0 THEN 1 ELSE RECEBIDOS END) AS DECIMAL) * 100) AS DECIMAL) [%Nível de serviço]
			FROM @TABLE1
			 ORDER BY Grupo,HORAMASK
			
	END
	
	